services:
  api:
    build:
      context: ./api
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      FRONT_DOMAIN: "localhost:$FRONT_PORT"
    volumes:
      - ./api:/app
    depends_on:
      - db
    ports:
      - "$API_PORT:3000"

  front:
    build:
      context: ./front
      args:
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    volumes:
      - ./front:/app
    tmpfs: /tmp
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api

  db:
    image: postgres:13.18-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
